title : Remosco - Réseau mondial Serge Moscovici
tagline: "Réseau mondial Serge Moscovici"
author :
  name : Antoine Cordelois
  email : cordelois.antoine+remosco@gmail.com
  github : eu
collections:
  - members
  - EASP
lang: fr
plugins: [ConcatArrays]
sass:
  sass_dir: assets/_sass
  style: compressed
paginate: 6
paginate_path: "/:num/"
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
production_url : http://remosco.com
